version: "3.9"
services:
  php:
    image: hsd18/phpdemo
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - frontend
      - backend
    depends_on:
      - mysql
      - phpmyadmin
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=moeuser
      - MYSQL_PASSWORD=moepass
      - MYSQL_DB=moe_db
    volumes:
      - .:/var/www/html/
    ports:
      - "30001:80"
  mysql:
    image: mysql:5.7
    networks:
      - backend
    deploy:
      mode: replicated
      replicas: 4
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=moeuser
      - MYSQL_PASSWORD=moepass
      - MYSQL_DATABASE=moe_db
    volumes:
      - .:/var/www/html/
      - ./employees.sql:/docker-entrypoint-initdb.d/employees.sql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    deploy:
      mode: replicated
      replicas: 4
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "30002:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT= 3306
    volumes:
      - /sessions
networks:
  frontend:
  backend:
